# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [11]:
import numpy as np 

#### 2. Print the numpy version and the configuration 

In [12]:
print("NumPy version:", np.__version__)
print("NumPy configuration:")
np.show_config()

NumPy version: 1.26.4
NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/TANISHA/anaconda3/Library/include
    lib directory: C:/Users/TANISHA/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    famil

#### 3. Create a null vector of size 10

In [13]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [14]:
array = np.array([1, 2, 3, 4, 5])
memory_size = array.nbytes
print("Memory size of the array:", memory_size, "bytes")

Memory size of the array: 20 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [15]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [16]:
null_vector = np.zeros(10)
null_vector[4] = 1 
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [17]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [18]:
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [20]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print("Indices of non-zero elements:", non_zero_indices)

Indices of non-zero elements: (array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [21]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [22]:
random_array_3x3x3 = np.random.random((3, 3, 3))
print("3x3x3 Array with Random Values:")
print(random_array_3x3x3)

3x3x3 Array with Random Values:
[[[0.18252445 0.52024615 0.65192647]
  [0.76401595 0.03278296 0.20444892]
  [0.4560825  0.17871036 0.5428913 ]]

 [[0.6866692  0.01402429 0.11566167]
  [0.31700837 0.41595896 0.3779497 ]
  [0.16312717 0.49431068 0.16021974]]

 [[0.83598683 0.39491449 0.68369484]
  [0.01366772 0.3541197  0.85754057]
  [0.17869954 0.2420907  0.93532183]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
random_array_10x10 = np.random.random((10, 10))
min_value = np.min(random_array_10x10)
max_value = np.max(random_array_10x10)
print("10x10 Array with Random Values:")
print(random_array_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

10x10 Array with Random Values:
[[0.54159805 0.89394959 0.75041862 0.06706568 0.70841383 0.36982078
  0.17345491 0.9611153  0.86711521 0.27837856]
 [0.81169366 0.50162149 0.52398736 0.499454   0.57744317 0.46055314
  0.4871677  0.10139852 0.30915384 0.19475953]
 [0.8847766  0.11416447 0.39542016 0.76775112 0.8559799  0.69767418
  0.69504536 0.47866803 0.66164407 0.6210383 ]
 [0.92090668 0.73366425 0.7373852  0.52409093 0.47337521 0.18309438
  0.94505672 0.21200439 0.71174694 0.679344  ]
 [0.87379168 0.55439096 0.62824945 0.83449753 0.18766915 0.34482928
  0.33696721 0.83757994 0.908179   0.62364429]
 [0.39531278 0.91783812 0.99022413 0.04667325 0.70940629 0.51333078
  0.79055331 0.12410342 0.47809313 0.9675712 ]
 [0.24026978 0.69761003 0.43339586 0.51096527 0.22058746 0.56870439
  0.03457087 0.24523066 0.69238784 0.04135735]
 [0.65659597 0.44434358 0.68455551 0.89341448 0.24854471 0.12568701
  0.59059197 0.39131882 0.07509549 0.44347518]
 [0.71608477 0.94792481 0.38721152 0.36181939 0.

#### 14. Create a random vector of size 30 and find the mean value

In [24]:
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Random Vector of Size 30:")
print(random_vector)
print("Mean value:", mean_value)

Random Vector of Size 30:
[0.40774859 0.55060132 0.09243631 0.27330628 0.71195109 0.56714678
 0.39986441 0.38883978 0.14364946 0.0615018  0.62020634 0.50708355
 0.23097518 0.74666319 0.92548433 0.37212889 0.25036036 0.37531764
 0.89847776 0.88743314 0.25182796 0.56014043 0.22299413 0.24848823
 0.55208685 0.93815117 0.74383328 0.19904449 0.2360591  0.55765276]
Mean value: 0.4640484876920893


#### 15. Create a 2d array with 1 on the border and 0 inside

In [25]:
size = 5
border_array = np.ones((size, size), dtype=int)
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on the Border and 0 Inside:")
print(border_array)

2D Array with 1 on the Border and 0 Inside:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [26]:
original_array = np.array([[1, 2], [3, 4]])
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
print("Original Array:")
print(original_array)
print("Array with Border Filled with 0's:")
print(bordered_array)

Original Array:
[[1 2]
 [3 4]]
Array with Border Filled with 0's:
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [27]:
result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = np.nan in set([np.nan])
result6 = 0.3 == 3 * 0.1
# nan ,false,false,nan,true,false
print("0 * np.nan:", result1)
print("np.nan == np.nan:", result2)
print("np.inf > np.nan:", result3)
print("np.nan - np.nan:", result4)
print("np.nan in set([np.nan]):", result5)
print("0.3 == 3 * 0.1:", result6)

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [28]:
matrix_5x5 = np.diag([1, 2, 3, 4], k=-1)
print(matrix_5x5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [29]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [30]:
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print("Index of the 100th element:", index)

Index of the 100th element: (1, 5, 4)
